#!/usr/bin/env bash
#
# tests/lib/orphan-probe.sh — the shared fixture behind the per-call-site
# "no descendant survives a watchdog timeout" regression tests (issue #251).
#
# WHY THIS FILE EXISTS
# --------------------
# tests/lib/watchdog.sh promises that a TIMED-OUT payload leaves no orphan: the
# reap signals the whole process GROUP, so the nested command substitution that
# does the expensive work — a grandchild of the backgrounded job — dies with it
# instead of reparenting to init and burning CPU (issue #188).
#
# Until now that promise was pinned only by tests/unit/watchdog.test.sh's
# synthetic `grandchild_ticker`, plus a point-in-time MANUAL check at each of
# the four real call sites. A manual check is a snapshot: nothing stops a later
# commit from introducing a process-group escape (`setsid`, `disown`, `nohup`,
# an own `set -m`, a background/double fork) into bin/persona.sh,
# bin/html-escape.sh or bin/report-writer.sh and silently bringing orphans back
# on exactly the failure path the watchdog exists to contain — with no test to
# catch it. This file is what makes each site's check committed and CI-enforced.
#
# It supplies the two things every such test needs:
#
#   1. A payload that ALWAYS overruns and stays OBSERVABLE after the kill. It
#      ticks a marker file from inside a NESTED COMMAND SUBSTITUTION, so the
#      ticker is a grandchild of whatever watchdog_run backgrounds — the exact
#      shape that used to be stranded. A reaped tree stops appending; a stranded
#      one keeps growing.
#   2. The assertion that reads that marker across a settle window.
#
# WHAT IS REAL AND WHAT IS A STAND-IN — be precise about this:
# each per-site test keeps that site's REAL wrapper and REAL process topology
# (render_tmpl_timed's source-a-script-then-call-a-function, run_voice_timed's
# `env … bash <script>`, escape_timed's bare function, report-writer's
# function → function → `bash <script>`). Only the innermost payload BODY is
# swapped for the ticker below, by pointing the site's existing script variable
# at a generated fixture (or, for the bare-function site, shadowing the payload
# function inside the test's own subshell). That swap is necessary, not
# cosmetic: the production bodies are correctly bounded and can no longer be
# made to hang, and inducing a hang would mean regressing production code. The
# invariant under test is the watchdog reaping THAT TOPOLOGY — which is exactly
# what the manual per-site check verified, and exactly what a future
# process-group escape would break. No production file is touched.

# orphan_probe_tick_forever <marker>
#
# The payload body: never terminates, and does its work inside a nested command
# substitution so the ticking process is a GRANDCHILD of the caller. Used
# directly where the real payload is a bare shell function; the generated script
# below embeds the same body for the `bash <script>` topologies.
orphan_probe_tick_forever() {
  local marker="$1" spin
  spin="$( while :; do printf 'tick\n' >>"$marker"; sleep 0.2; done )"
  printf '%s' "$spin"
}

# orphan_probe_tick_count <marker> — lines currently in the marker file (0 when
# absent). Liveness is measured by growth, so this must never fail the caller.
orphan_probe_tick_count() {
  [ -f "$1" ] && wc -l <"$1" | tr -d ' ' || printf '0'
}

# orphan_probe_write_script <path> <marker> [fn_name]
#
# Generate an executable bash script at <path> that stands in for a production
# script at a call site. It mirrors the real scripts' dual surface exactly
# (bin/persona.sh:423, bin/html-escape.sh:266): sourcing it only DEFINES
# <fn_name> (default `orphan_probe_payload`), while executing it RUNS the
# ticker — so one generator serves both the "source it, then call a function"
# and the "`bash` the script" topologies.
#
# <marker> is baked in at generation time (shell-quoted with %q), so the fixture
# needs no argv or environment plumbing and ignores whatever real argv the call
# site passes through.
orphan_probe_write_script() {
  local path="$1" marker="$2" fn="${3:-orphan_probe_payload}"
  # Every single-quoted line below is the GENERATED script's source text, not an
  # expression for this shell: `$spin`, `$orphan_probe_marker`, `${BASH_SOURCE[0]}`
  # and `$@` must reach the file unexpanded and be resolved when the fixture RUNS.
  # Only the marker (baked in with %q) and the function name are interpolated here.
  # shellcheck disable=SC2016  # deliberate: these are generated-script literals, not expressions to expand now
  {
    printf '%s\n' '#!/usr/bin/env bash'
    printf '%s\n' '# GENERATED by orphan_probe_write_script (tests/lib/orphan-probe.sh).'
    printf '%s\n' '# A never-terminating stand-in payload for a watchdog timeout test.'
    printf 'orphan_probe_marker=%q\n' "$marker"
    printf '%s\n' "${fn}() {"
    printf '%s\n' '  local spin'
    printf '%s\n' '  spin="$( while :; do printf "tick\n" >>"$orphan_probe_marker"; sleep 0.2; done )"'
    printf '%s\n' '  printf "%s" "$spin"'
    printf '%s\n' '}'
    # Same CLI guard as the production scripts this stands in for: sourced →
    # define only; executed → run.
    printf '%s\n' 'if [ "${BASH_SOURCE[0]}" = "${0}" ]; then'
    printf '%s\n' "  ${fn} \"\$@\""
    printf '%s\n' 'fi'
  } >"$path"
  chmod +x "$path"
}

# orphan_probe_no_survivors <marker> [settle_secs]
#
# The assertion, as a predicate: returns 0 when the watchdog reaped the whole
# tree, 1 (with a diagnostic on stderr) when it did not. Call it AFTER the
# watchdog has returned 124.
#
# Two conditions, both required:
#
#   * the marker must already have ticked at least once — otherwise a fixture
#     that never ran would make a "the count stayed flat" check pass while
#     proving nothing (0 → 0). This is the fail-closed half: no evidence of a
#     live payload is a FAILURE, never a silent pass.
#   * the count must then stay flat across the settle window — a stranded
#     grandchild keeps appending, so growth means an orphan survived.
#
# The default 2 s window is several ticks wide at the fixture's 0.2 s cadence,
# so a survivor is caught rather than raced past.
orphan_probe_no_survivors() {
  local marker="$1" settle="${2:-2}" before after
  before="$(orphan_probe_tick_count "$marker")"
  if [ "$before" -lt 1 ]; then
    printf '  orphan probe never ticked (%s) — the payload did not run, so "no survivors" proves nothing\n' \
      "$marker" >&2
    return 1
  fi
  sleep "$settle"
  after="$(orphan_probe_tick_count "$marker")"
  if [ "$before" = "$after" ]; then
    return 0
  fi
  printf '  a descendant survived the watchdog: marker kept growing (%s → %s ticks over %ss)\n' \
    "$before" "$after" "$settle" >&2
  return 1
}
