#!/usr/bin/env bash
#
# tests/unit/report-writer.test.sh — unit tests for bin/report-writer.sh, the
# report-assembly + output-path helper (issue #46).
#
# Follows the repo test-harness convention (issue #4, tests/lib/assert.sh): raw
# bash with `set -euo pipefail`, sources tests/lib/assert.sh, defines `test_*`
# functions, ends with `run_tests`. scripts/test.sh auto-discovers it via the
# `*.test.sh` glob — run the whole suite with `scripts/test.sh`, this file alone
# with `scripts/test.sh tests/unit/report-writer.test.sh`, or directly with
# `bash tests/unit/report-writer.test.sh`.
#
# Seams used:
#   * YNAB_CONFIG_FILE — the loader's documented test seam (a sandbox config), so
#     the .report.output_dir read is deterministic.
#   * HOME             — overridden to the sandbox so the ~-based default path and
#     ~ expansion never touch the real home directory.
#   * --template / --output-dir flags — point the writer at a tiny fixture
#     template and sandbox dirs, keeping each scenario isolated.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
source "$REPO_ROOT/tests/lib/assert.sh"

WRITER="$REPO_ROOT/bin/report-writer.sh"
REAL_TEMPLATE="$REPO_ROOT/assets/report/template.html"

SANDBOX="$(mktemp -d)"
trap 'rm -rf "$SANDBOX"' EXIT

# A tiny fixture template with three block slots + the three scalar slots, so the
# behavioural tests are not coupled to the real template's full slot list. The
# writer derives "required" from whatever the template declares.
FIXTURE_TEMPLATE="$SANDBOX/template.html"
cat > "$FIXTURE_TEMPLATE" <<'HTML'
<!DOCTYPE html><html><head>
<title>{{tier}} YNAB Review — {{report_date}}</title>
<meta name="report-output-path" content="{{output_path}}">
</head><body>
<section class="section"><!-- SLOT:kpi-dashboard --></section>
<section class="section"><!-- SLOT:section-1-classification --></section>
<footer class="print-footer">Generated by <!-- SLOT:footer-persona --></footer>
</body></html>
HTML

# The fixture template's three block slots, as `--slot name=value` argv, with
# real-ish HTML so substitution faithfulness is exercised.
fixture_slots() {
  printf '%s\0' \
    '--slot' 'kpi-dashboard=<div class="kpi-grid"><div class="kpi">Income 1,234</div></div>' \
    '--slot' 'section-1-classification=<div class="card"><h2>Classification</h2></div>' \
    '--slot' 'footer-persona=Hobbes'
}

# Run the writer with the fixture template + fixture slots, plus any extra argv.
# Reads NUL-delimited args so HTML values with spaces/'=' survive intact.
run_writer_fixture() {
  local args=()
  while IFS= read -r -d '' a; do args+=("$a"); done < <(fixture_slots)
  YNAB_CONFIG_FILE="${YNAB_CONFIG_FILE:-$SANDBOX/none.json}" \
    bash "$WRITER" --template "$FIXTURE_TEMPLATE" "$@" "${args[@]}"
}

# (a) AC: default path applied when .report.output_dir is absent from config.
#     HOME → sandbox, so the ~/Documents/Claude/Reports default lands in sandbox.
test_default_path_when_config_absent() {
  local out
  out="$(HOME="$SANDBOX" YNAB_CONFIG_FILE="$SANDBOX/missing.json" \
          run_writer_fixture --tier Weekly --date 2026-06-22)"
  assert_eq "$SANDBOX/Documents/Claude/Reports/YNAB-Weekly-Review-2026-06-22.html" "$out" \
    "default ~/Documents/Claude/Reports applied + filename built"
  assert_file_exists "$out"
}

# (b) AC: custom configured path used when .report.output_dir is present.
test_custom_path_from_config() {
  local cfg="$SANDBOX/with-dir.json" dir="$SANDBOX/configured-reports" out
  cat > "$cfg" <<JSON
{ "report": { "output_dir": "$dir" } }
JSON
  out="$(YNAB_CONFIG_FILE="$cfg" run_writer_fixture --tier Monthly --date 2026-01-31)"
  assert_eq "$dir/YNAB-Monthly-Review-2026-01-31.html" "$out" "configured output_dir used"
  assert_file_exists "$out"
}

# (c) AC: missing required slot (not marked `no findings`) → non-zero, no file.
test_missing_slot_fails_and_writes_nothing() {
  local dir="$SANDBOX/should-stay-empty" rc=0 err
  # Only two of the fixture's three block slots supplied — footer-persona omitted.
  err="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$dir" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-dashboard=<div>x</div>' \
            --slot 'section-1-classification=<div>y</div>' 2>&1 )" || rc=$?
  assert_eq "1" "$rc" "exit code is non-zero (1) on a missing required slot"
  assert_contains "$err" "footer-persona" "error names the missing slot"
  # No file — and the writer must not even create the output file.
  [ -e "$dir/YNAB-Weekly-Review-2026-06-22.html" ] \
    && fail "writer wrote a file despite a missing required slot"
  return 0
}

# An empty value (without the sentinel) is treated as missing — no partial files.
test_empty_value_is_treated_as_missing() {
  local rc=0 err
  err="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$SANDBOX/empties" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-dashboard=<div>x</div>' \
            --slot 'section-1-classification=<div>y</div>' \
            --slot 'footer-persona=' 2>&1 )" || rc=$?
  assert_eq "1" "$rc" "empty slot value (no sentinel) is rejected"
  assert_contains "$err" "footer-persona" "error names the empty slot"
  # "no partial files" must hold for an empty value too — assert nothing written.
  [ -e "$SANDBOX/empties/YNAB-Weekly-Review-2026-06-22.html" ] \
    && fail "writer wrote a file despite an empty (un-sentineled) slot"
  return 0
}

# `no findings` is the explicit "intentionally empty" sentinel: it satisfies the
# completeness check and renders as an empty section (no literal text leaks).
test_no_findings_sentinel_allows_write() {
  local dir="$SANDBOX/sentinel" out body
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$dir" \
            --tier Annual --date 2026-12-31 \
            --slot 'kpi-dashboard=<div>k</div>' \
            --slot 'section-1-classification=no findings' \
            --slot 'footer-persona=Hobbes' )"
  assert_file_exists "$out"
  body="$(cat "$out")"
  assert_contains "$body" '<section class="section"></section>' "sentinel slot rendered empty"
  case "$body" in *"no findings"*) fail "literal 'no findings' leaked into the report" ;; esac
}

# Filename format, ~ expansion, and trailing-slash tolerance all at once.
test_tilde_and_trailing_slash() {
  local out
  # The literal ~ is the value UNDER TEST — the writer expands it, not the shell.
  # shellcheck disable=SC2088
  out="$( HOME="$SANDBOX" YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Quarterly-Tax --date 2026-04-15 \
            --output-dir '~/reports/' )"
  assert_eq "$SANDBOX/reports/YNAB-Quarterly-Tax-Review-2026-04-15.html" "$out" \
    "~ expanded, trailing slash collapsed, tier kept verbatim in filename"
  assert_file_exists "$out"
}

# Scalar slots substituted; no slot comment or mustache placeholder survives.
test_scalar_slots_substituted() {
  local out body
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Monthly --date 2026-02-28 \
            --output-dir "$SANDBOX/scalars" )"
  body="$(cat "$out")"
  assert_contains "$body" "Monthly YNAB Review — 2026-02-28" "{{tier}} + {{report_date}} substituted"
  assert_contains "$body" "content=\"$out\"" "{{output_path}} substituted with the saved path"
  case "$body" in *"<!-- SLOT:"*) fail "an unfilled SLOT comment survived" ;; esac
  case "$body" in *"{{"*) fail "an unfilled {{scalar}} placeholder survived" ;; esac
}

# Bad tier / bad date / unknown slot are usage errors (exit 2).
test_usage_errors() {
  local rc=0
  rc=0; YNAB_CONFIG_FILE="$SANDBOX/none.json" run_writer_fixture --tier Daily --date 2026-06-22 >/dev/null 2>&1 || rc=$?
  assert_eq "2" "$rc" "invalid tier → exit 2"
  rc=0; YNAB_CONFIG_FILE="$SANDBOX/none.json" run_writer_fixture --tier Weekly --date 06-22-2026 >/dev/null 2>&1 || rc=$?
  assert_eq "2" "$rc" "invalid date → exit 2"
  rc=0
  YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" --template "$FIXTURE_TEMPLATE" \
    --output-dir "$SANDBOX/u" --tier Weekly --date 2026-06-22 \
    --slot 'kpi-dashboard=a' --slot 'section-1-classification=b' \
    --slot 'footer-persona=c' --slot 'no-such-slot=x' >/dev/null 2>&1 || rc=$?
  assert_eq "2" "$rc" "unknown slot name → exit 2"
}

# Integration against the REAL frozen template: all 14 slots filled, nothing left.
test_real_template_all_slots() {
  local dir="$SANDBOX/real" out body
  assert_file_exists "$REAL_TEMPLATE"
  local args=()
  local s
  for s in kpi-dashboard \
           section-1-classification section-2-income section-3-spending \
           section-4-budget-adherence section-5-cash-flow section-6-categories \
           section-7-accounts section-8-goals section-9-net-worth \
           section-10-anomalies section-11-recommendations section-12-tax-summary \
           footer-persona; do
    args+=( --slot "$s=<!-- filled:$s -->" )
  done
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$REAL_TEMPLATE" --output-dir "$dir" \
            --tier Annual --date 2026-12-31 "${args[@]}" )"
  assert_eq "$dir/YNAB-Annual-Review-2026-12-31.html" "$out" "real-template report path"
  body="$(cat "$out")"
  case "$body" in *"<!-- SLOT:"*) fail "a real-template SLOT comment was left unfilled" ;; esac
  case "$body" in *"{{tier}}"*|*"{{report_date}}"*|*"{{output_path}}"*) fail "a real-template scalar slot survived" ;; esac
  assert_contains "$body" "Annual YNAB Review" "real-template header tier filled"
}

# A typo'd required-slot name must surface as an UNKNOWN name, not silently hide
# behind the real slot's "missing" report — else the caller never sees the typo.
test_slot_typo_surfaces_unknown_name() {
  local dir="$SANDBOX/typo" rc=0 err
  # kpi-dashboard MISSPELLED kpi-dashboad: the real slot is now unfilled, and the
  # typo'd name is unknown to the template. (Neither name is a substring of the
  # other, so each assertion below is unambiguous.)
  err="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$dir" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-dashboad=<div>x</div>' \
            --slot 'section-1-classification=<div>y</div>' \
            --slot 'footer-persona=Hobbes' 2>&1 )" || rc=$?
  assert_eq "1" "$rc" "a missing real slot still sets exit 1 even with a typo present"
  assert_contains "$err" "kpi-dashboad" "error surfaces the unknown (typo'd) slot name"
  assert_contains "$err" "kpi-dashboard" "error still names the genuinely-missing slot"
  [ -e "$dir/YNAB-Weekly-Review-2026-06-22.html" ] \
    && fail "writer wrote a file despite a typo'd slot"
  return 0
}

# An invalid --slot name (glob metachar / uppercase) is rejected at PARSE time
# (exit 2) so it can never reach the literal substitution needle.
test_invalid_slot_name_rejected_at_parse() {
  local rc=0 err
  err="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$SANDBOX/badname" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-*=<div>x</div>' 2>&1 )" || rc=$?
  assert_eq "2" "$rc" "glob-metachar slot name → usage error (exit 2)"
  assert_contains "$err" "invalid --slot name" "error explains the bad slot name"
}

# A configured output_dir that expands to empty (e.g. an unset $VAR) is refused
# rather than silently writing to the filesystem root.
test_empty_output_dir_is_rejected() {
  local cfg="$SANDBOX/empty-dir.json" rc=0 err
  cat > "$cfg" <<'JSON'
{ "report": { "output_dir": "$YNAB_NOPE_UNSET_VAR" } }
JSON
  err="$( YNAB_CONFIG_FILE="$cfg" run_writer_fixture --tier Weekly --date 2026-06-22 2>&1 )" || rc=$?
  assert_eq "2" "$rc" "output dir resolving to empty → usage error (exit 2)"
  assert_contains "$err" "output dir resolved to empty" "error explains the empty output dir"
}

run_tests
