#!/usr/bin/env bash
#
# tests/unit/report-writer.test.sh — unit tests for bin/report-writer.sh, the
# report-assembly + output-path helper (issue #46).
#
# Follows the repo test-harness convention (issue #4, tests/lib/assert.sh): raw
# bash with `set -euo pipefail`, sources tests/lib/assert.sh, defines `test_*`
# functions, ends with `run_tests`. scripts/test.sh auto-discovers it via the
# `*.test.sh` glob — run the whole suite with `scripts/test.sh`, this file alone
# with `scripts/test.sh tests/unit/report-writer.test.sh`, or directly with
# `bash tests/unit/report-writer.test.sh`.
#
# Seams used:
#   * YNAB_CONFIG_FILE — the loader's documented test seam (a sandbox config), so
#     the .report.output_dir read is deterministic.
#   * HOME             — overridden to the sandbox so the ~-based default path and
#     ~ expansion never touch the real home directory.
#   * --template / --output-dir flags — point the writer at a tiny fixture
#     template and sandbox dirs, keeping each scenario isolated.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
source "$REPO_ROOT/tests/lib/assert.sh"

WRITER="$REPO_ROOT/bin/report-writer.sh"
REAL_TEMPLATE="$REPO_ROOT/assets/report/template.html"

SANDBOX="$(mktemp -d)"
trap 'rm -rf "$SANDBOX"' EXIT

# Sandbox HOME for the WHOLE file (not just the default-path tests): every writer
# invocation inherits it, so a resolution regression can only ever fall back to
# $SANDBOX/Documents/Claude/Reports — never the developer's real ~/Documents. The
# handful of tests that also set HOME inline (they assert on the ~-default) keep
# doing so for local clarity; this is the belt-and-braces guarantee.
export HOME="$SANDBOX"

# A tiny fixture template with three block slots + the three scalar slots, so the
# behavioural tests are not coupled to the real template's full slot list. The
# writer derives "required" from whatever the template declares.
FIXTURE_TEMPLATE="$SANDBOX/template.html"
cat > "$FIXTURE_TEMPLATE" <<'HTML'
<!DOCTYPE html><html><head>
<title>{{tier}} YNAB Review — {{report_date}}</title>
<meta name="report-output-path" content="{{output_path}}">
</head><body>
<section class="section"><!-- SLOT:kpi-dashboard --></section>
<section class="section"><!-- SLOT:section-1-classification --></section>
<footer class="print-footer">Generated by <!-- SLOT:footer-persona --></footer>
</body></html>
HTML

# The fixture template's three block slots, as `--slot name=value` argv, with
# real-ish HTML so substitution faithfulness is exercised.
fixture_slots() {
  printf '%s\0' \
    '--slot' 'kpi-dashboard=<div class="kpi-grid"><div class="kpi">Income 1,234</div></div>' \
    '--slot' 'section-1-classification=<div class="card"><h2>Classification</h2></div>' \
    '--slot' 'footer-persona=Hobbes'
}

# Run the writer with the fixture template + fixture slots, plus any extra argv.
# Reads NUL-delimited args so HTML values with spaces/'=' survive intact.
run_writer_fixture() {
  local args=()
  while IFS= read -r -d '' a; do args+=("$a"); done < <(fixture_slots)
  YNAB_CONFIG_FILE="${YNAB_CONFIG_FILE:-$SANDBOX/none.json}" \
    bash "$WRITER" --template "$FIXTURE_TEMPLATE" "$@" "${args[@]}"
}

# (a) AC: default path applied when .report.output_dir is absent from config.
#     HOME → sandbox, so the ~/Documents/Claude/Reports default lands in sandbox.
test_default_path_when_config_absent() {
  local out
  out="$(HOME="$SANDBOX" YNAB_CONFIG_FILE="$SANDBOX/missing.json" \
          run_writer_fixture --tier Weekly --date 2026-06-22)"
  assert_eq "$SANDBOX/Documents/Claude/Reports/YNAB-Weekly-Review-2026-06-22.html" "$out" \
    "default ~/Documents/Claude/Reports applied + filename built"
  assert_file_exists "$out"
}

# (b) AC: custom configured path used when .report.output_dir is present.
test_custom_path_from_config() {
  local cfg="$SANDBOX/with-dir.json" dir="$SANDBOX/configured-reports" out
  cat > "$cfg" <<JSON
{ "report": { "output_dir": "$dir" } }
JSON
  out="$(YNAB_CONFIG_FILE="$cfg" run_writer_fixture --tier Monthly --date 2026-01-31)"
  assert_eq "$dir/YNAB-Monthly-Review-2026-01-31.html" "$out" "configured output_dir used"
  assert_file_exists "$out"
}

# (c) AC: missing required slot (not marked `no findings`) → non-zero, no file.
test_missing_slot_fails_and_writes_nothing() {
  local dir="$SANDBOX/should-stay-empty" rc=0 out err
  # Only two of the fixture's three block slots supplied — footer-persona omitted.
  # stdout and stderr captured SEPARATELY so we can assert the error text AND
  # that no success path leaked to stdout.
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$dir" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-dashboard=<div>x</div>' \
            --slot 'section-1-classification=<div>y</div>' 2>"$SANDBOX/missing.err" )" || rc=$?
  err="$(cat "$SANDBOX/missing.err")"
  assert_eq "1" "$rc" "exit code is non-zero (1) on a missing required slot"
  assert_eq "" "$out" "no success path leaked to stdout on a missing slot"
  assert_contains "$err" "footer-persona" "error names the missing slot"
  # No file — and the writer must not even create the output file.
  [ -e "$dir/YNAB-Weekly-Review-2026-06-22.html" ] \
    && fail "writer wrote a file despite a missing required slot"
  return 0
}

# An empty value (without the sentinel) is treated as missing — no partial files.
test_empty_value_is_treated_as_missing() {
  local rc=0 out err
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$SANDBOX/empties" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-dashboard=<div>x</div>' \
            --slot 'section-1-classification=<div>y</div>' \
            --slot 'footer-persona=' 2>"$SANDBOX/empty.err" )" || rc=$?
  err="$(cat "$SANDBOX/empty.err")"
  assert_eq "1" "$rc" "empty slot value (no sentinel) is rejected"
  assert_eq "" "$out" "no success path leaked to stdout on an empty slot"
  assert_contains "$err" "footer-persona" "error names the empty slot"
  # "no partial files" must hold for an empty value too — assert nothing written.
  [ -e "$SANDBOX/empties/YNAB-Weekly-Review-2026-06-22.html" ] \
    && fail "writer wrote a file despite an empty (un-sentineled) slot"
  return 0
}

# A whitespace-only value ("   ") is trimmed and judged empty — the completeness
# guard must reject it (no silently-blank section), exactly like an empty value.
test_whitespace_only_slot_is_treated_as_missing() {
  local dir="$SANDBOX/whitespace" rc=0 out err
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$dir" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-dashboard=<div>x</div>' \
            --slot 'section-1-classification=<div>y</div>' \
            --slot 'footer-persona=   ' 2>"$SANDBOX/ws.err" )" || rc=$?
  err="$(cat "$SANDBOX/ws.err")"
  assert_eq "1" "$rc" "a whitespace-only slot value is rejected as missing"
  assert_eq "" "$out" "no success path leaked to stdout on a whitespace-only slot"
  assert_contains "$err" "footer-persona" "error names the blank slot"
  [ -e "$dir/YNAB-Weekly-Review-2026-06-22.html" ] \
    && fail "writer wrote a file despite a whitespace-only slot"
  return 0
}

# `no findings` is the explicit "intentionally empty" sentinel: it satisfies the
# completeness check and renders as an empty section (no literal text leaks).
test_no_findings_sentinel_allows_write() {
  local dir="$SANDBOX/sentinel" out body
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$dir" \
            --tier Annual --date 2026-12-31 \
            --slot 'kpi-dashboard=<div>k</div>' \
            --slot 'section-1-classification=no findings' \
            --slot 'footer-persona=Hobbes' )"
  assert_file_exists "$out"
  body="$(cat "$out")"
  assert_contains "$body" '<section class="section"></section>' "sentinel slot rendered empty"
  case "$body" in *"no findings"*) fail "literal 'no findings' leaked into the report" ;; esac
}

# Filename format, ~ expansion, and trailing-slash tolerance all at once.
test_tilde_and_trailing_slash() {
  local out
  # The literal ~ is the value UNDER TEST — the writer expands it, not the shell.
  # shellcheck disable=SC2088
  out="$( HOME="$SANDBOX" YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Quarterly-Tax --date 2026-04-15 \
            --output-dir '~/reports/' )"
  assert_eq "$SANDBOX/reports/YNAB-Quarterly-Tax-Review-2026-04-15.html" "$out" \
    "~ expanded, trailing slash collapsed, tier kept verbatim in filename"
  assert_file_exists "$out"
}

# Scalar slots substituted; no slot comment or mustache placeholder survives.
test_scalar_slots_substituted() {
  local out body
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Monthly --date 2026-02-28 \
            --output-dir "$SANDBOX/scalars" )"
  body="$(cat "$out")"
  assert_contains "$body" "Monthly YNAB Review — 2026-02-28" "{{tier}} + {{report_date}} substituted"
  assert_contains "$body" "content=\"$out\"" "{{output_path}} substituted with the saved path"
  case "$body" in *"<!-- SLOT:"*) fail "an unfilled SLOT comment survived" ;; esac
  case "$body" in *"{{"*) fail "an unfilled {{scalar}} placeholder survived" ;; esac
}

# Bad tier / bad date / unknown slot are usage errors (exit 2).
test_usage_errors() {
  local rc=0
  rc=0; YNAB_CONFIG_FILE="$SANDBOX/none.json" run_writer_fixture --tier Daily --date 2026-06-22 >/dev/null 2>&1 || rc=$?
  assert_eq "2" "$rc" "invalid tier → exit 2"
  rc=0; YNAB_CONFIG_FILE="$SANDBOX/none.json" run_writer_fixture --tier Weekly --date 06-22-2026 >/dev/null 2>&1 || rc=$?
  assert_eq "2" "$rc" "invalid date → exit 2"
  rc=0
  YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" --template "$FIXTURE_TEMPLATE" \
    --output-dir "$SANDBOX/u" --tier Weekly --date 2026-06-22 \
    --slot 'kpi-dashboard=a' --slot 'section-1-classification=b' \
    --slot 'footer-persona=c' --slot 'no-such-slot=x' >/dev/null 2>&1 || rc=$?
  assert_eq "2" "$rc" "unknown slot name → exit 2"
}

# Integration against the REAL frozen template: all 14 slots filled, nothing left.
test_real_template_all_slots() {
  local dir="$SANDBOX/real" out body
  assert_file_exists "$REAL_TEMPLATE"
  local args=()
  local s
  for s in kpi-dashboard \
           section-1-classification section-2-income section-3-spending \
           section-4-budget-adherence section-5-cash-flow section-6-categories \
           section-7-accounts section-8-goals section-9-net-worth \
           section-10-anomalies section-11-recommendations section-12-tax-summary \
           footer-persona; do
    args+=( --slot "$s=<!-- filled:$s -->" )
  done
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$REAL_TEMPLATE" --output-dir "$dir" \
            --tier Annual --date 2026-12-31 "${args[@]}" )"
  assert_eq "$dir/YNAB-Annual-Review-2026-12-31.html" "$out" "real-template report path"
  body="$(cat "$out")"
  case "$body" in *"<!-- SLOT:"*) fail "a real-template SLOT comment was left unfilled" ;; esac
  case "$body" in *"{{tier}}"*|*"{{report_date}}"*|*"{{output_path}}"*) fail "a real-template scalar slot survived" ;; esac
  assert_contains "$body" "Annual YNAB Review" "real-template header tier filled"
}

# A typo'd required-slot name must surface as an UNKNOWN name, not silently hide
# behind the real slot's "missing" report — else the caller never sees the typo.
test_slot_typo_surfaces_unknown_name() {
  local dir="$SANDBOX/typo" rc=0 out err
  # kpi-dashboard MISSPELLED kpi-dashboad: the real slot is now unfilled, and the
  # typo'd name is unknown to the template. (Neither name is a substring of the
  # other, so each assertion below is unambiguous.)
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$dir" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-dashboad=<div>x</div>' \
            --slot 'section-1-classification=<div>y</div>' \
            --slot 'footer-persona=Hobbes' 2>"$SANDBOX/typo.err" )" || rc=$?
  err="$(cat "$SANDBOX/typo.err")"
  assert_eq "1" "$rc" "a missing real slot still sets exit 1 even with a typo present"
  assert_eq "" "$out" "no success path leaked to stdout on a typo'd slot"
  assert_contains "$err" "kpi-dashboad" "error surfaces the unknown (typo'd) slot name"
  assert_contains "$err" "kpi-dashboard" "error still names the genuinely-missing slot"
  [ -e "$dir/YNAB-Weekly-Review-2026-06-22.html" ] \
    && fail "writer wrote a file despite a typo'd slot"
  return 0
}

# An invalid --slot name (glob metachar / uppercase) is rejected at PARSE time
# (exit 2) so it can never reach the literal substitution needle.
test_invalid_slot_name_rejected_at_parse() {
  local rc=0 err
  err="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$SANDBOX/badname" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-*=<div>x</div>' 2>&1 )" || rc=$?
  assert_eq "2" "$rc" "glob-metachar slot name → usage error (exit 2)"
  assert_contains "$err" "invalid --slot name" "error explains the bad slot name"
}

# A configured output_dir that expands to empty (e.g. an unset $VAR) is refused
# rather than silently writing to the filesystem root.
test_empty_output_dir_is_rejected() {
  local cfg="$SANDBOX/empty-dir.json" rc=0 err
  cat > "$cfg" <<'JSON'
{ "report": { "output_dir": "$YNAB_NOPE_UNSET_VAR" } }
JSON
  err="$( YNAB_CONFIG_FILE="$cfg" run_writer_fixture --tier Weekly --date 2026-06-22 2>&1 )" || rc=$?
  assert_eq "2" "$rc" "output dir resolving to empty → usage error (exit 2)"
  assert_contains "$err" "output dir resolved to empty" "error explains the empty output dir"
}

# Regression for the write-failure gate (prior round's blocker #1): when the
# output dir cannot be created — its parent is a regular FILE, so `mkdir -p`
# fails deterministically for any user — the writer must exit non-zero, write NO
# file, and print NOTHING to stdout. Every "writes nothing" test above stops at
# the pre-write completeness check; this one exercises the write path itself.
test_write_failure_gate() {
  local blocker="$SANDBOX/not-a-dir" rc=0 out
  : > "$blocker"                       # a regular file where a directory is needed
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$blocker/sub" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-dashboard=<div>k</div>' \
            --slot 'section-1-classification=<div>s</div>' \
            --slot 'footer-persona=Hobbes' 2>/dev/null )" || rc=$?
  [ "$rc" -ne 0 ] || fail "writer must exit non-zero when the output dir can't be created"
  assert_eq "" "$out" "no success path leaked to stdout on a write failure"
  [ -e "$blocker/sub/YNAB-Weekly-Review-2026-06-22.html" ] \
    && fail "writer wrote a file despite a write failure"
  return 0
}

# Multiple trailing slashes collapse to a single separator (the pre-fix
# `${out_dir%/}` only stripped one — this guards the loop that strips them all).
test_multi_trailing_slash_collapsed() {
  local out
  out="$( HOME="$SANDBOX" YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Weekly --date 2026-06-22 \
            --output-dir "$SANDBOX/multi///" )"
  assert_eq "$SANDBOX/multi/YNAB-Weekly-Review-2026-06-22.html" "$out" \
    "multiple trailing slashes collapsed to a single path separator"
  assert_file_exists "$out"
}

# .report.template_path is resolved from config when --template is absent.
test_template_path_from_config() {
  local cfg="$SANDBOX/tmpl.json" out args=()
  cat > "$cfg" <<JSON
{ "report": { "template_path": "$FIXTURE_TEMPLATE" } }
JSON
  while IFS= read -r -d '' a; do args+=("$a"); done < <(fixture_slots)
  out="$( YNAB_CONFIG_FILE="$cfg" bash "$WRITER" \
            --output-dir "$SANDBOX/tmpl-out" \
            --tier Weekly --date 2026-06-22 "${args[@]}" )"
  assert_eq "$SANDBOX/tmpl-out/YNAB-Weekly-Review-2026-06-22.html" "$out" \
    ".report.template_path used when --template is absent"
  assert_file_exists "$out"
}

# With neither --template nor .report.template_path, the bundled asset template
# (assets/report/template.html) is the fallback — pass its full real slot set.
test_bundled_default_template_fallback() {
  local dir="$SANDBOX/bundled" out args=() s
  for s in kpi-dashboard \
           section-1-classification section-2-income section-3-spending \
           section-4-budget-adherence section-5-cash-flow section-6-categories \
           section-7-accounts section-8-goals section-9-net-worth \
           section-10-anomalies section-11-recommendations section-12-tax-summary \
           footer-persona; do
    args+=( --slot "$s=<!-- filled:$s -->" )
  done
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --output-dir "$dir" --tier Weekly --date 2026-06-22 "${args[@]}" )"
  assert_eq "$dir/YNAB-Weekly-Review-2026-06-22.html" "$out" \
    "bundled default template used when neither flag nor config sets one"
  assert_file_exists "$out"
}

# A configured/flag template that does not exist is a usage error (exit 2).
test_template_not_found_is_usage_error() {
  local rc=0 err
  # The trailing --template overrides run_writer_fixture's fixture path.
  err="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --template "$SANDBOX/does-not-exist.html" \
            --tier Weekly --date 2026-06-22 2>&1 )" || rc=$?
  assert_eq "2" "$rc" "a nonexistent template → usage error (exit 2)"
  assert_contains "$err" "template not found" "error explains the missing template"
}

# {{tier}} renders the friendly display name (Quarterly-Tax → "Quarterly Tax"),
# while the filename keeps the hyphenated enum.
test_quarterly_tax_display_name() {
  local dir="$SANDBOX/qt" out body
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Quarterly-Tax --date 2026-04-15 \
            --output-dir "$dir" )"
  assert_eq "$dir/YNAB-Quarterly-Tax-Review-2026-04-15.html" "$out" \
    "filename keeps the hyphenated Quarterly-Tax enum"
  body="$(cat "$out")"
  assert_contains "$body" "Quarterly Tax YNAB Review" "{{tier}} renders the friendly 'Quarterly Tax'"
  case "$body" in *"Quarterly-Tax YNAB Review"*) fail "hyphenated enum leaked into the {{tier}} display" ;; esac
}

# The writer HTML-escapes {{output_path}} — a configured path with HTML
# metacharacters must never break out of the meta attribute / inject an element.
test_output_path_is_html_escaped() {
  # The leading '&' also guards bash 5.2's patsub_replacement: a literal '&' in a
  # ${var//pat/repl} replacement must NOT expand to the matched text (which would
  # yield `<lt;` instead of `&lt;` and defeat the escaping).
  local danger='inj&"><script>x' dir out body
  dir="$SANDBOX/$danger"               # a single dir component (no '/'), dangerous chars
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Weekly --date 2026-06-22 --output-dir "$dir" )"
  assert_file_exists "$out"
  body="$(cat "$out")"
  assert_contains "$body" 'inj&amp;&quot;&gt;&lt;script&gt;x' "output path is HTML-escaped in the report"
  case "$body" in
    *'"><script>x'*) fail "unescaped output path broke out of the attribute (element injection)" ;;
    *'<lt;'*|*'>gt;'*) fail "patsub_replacement corrupted the HTML entities (& → matched text)" ;;
  esac
}

# An output dir resolving to the bare filesystem root is refused (exit 2), never
# written to as "/YNAB-…html".
test_root_output_dir_is_rejected() {
  local rc=0 err
  err="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Weekly --date 2026-06-22 --output-dir '/' 2>&1 )" || rc=$?
  assert_eq "2" "$rc" "output dir resolving to '/' → usage error (exit 2)"
  assert_contains "$err" "filesystem root" "error explains the root refusal"
}

# Out-of-range dates (month 13, day 39) are rejected, not just malformed shapes.
test_out_of_range_date_is_rejected() {
  local rc
  rc=0; YNAB_CONFIG_FILE="$SANDBOX/none.json" run_writer_fixture --tier Weekly --date 2026-13-01 >/dev/null 2>&1 || rc=$?
  assert_eq "2" "$rc" "month 13 → exit 2"
  rc=0; YNAB_CONFIG_FILE="$SANDBOX/none.json" run_writer_fixture --tier Weekly --date 2026-06-39 >/dev/null 2>&1 || rc=$?
  assert_eq "2" "$rc" "day 39 → exit 2"
}

# Regression: when the target path already exists as a DIRECTORY, `mv file dir`
# on BSD/macOS moves the temp file *into* it and exits 0 — a false success. The
# writer must refuse (non-zero), print no path, and leave no report file at the
# target. Gating test for the pre-`mv` "not a regular file" guard.
test_pre_existing_dir_at_target_is_refused() {
  local dir="$SANDBOX/dir-target" rc=0 out err target
  target="$dir/YNAB-Weekly-Review-2026-06-22.html"
  mkdir -p "$target"                   # the exact deterministic filename, as a directory
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$dir" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-dashboard=<div>k</div>' \
            --slot 'section-1-classification=<div>s</div>' \
            --slot 'footer-persona=Hobbes' 2>"$SANDBOX/dir-target.err" )" || rc=$?
  err="$(cat "$SANDBOX/dir-target.err")"
  [ "$rc" -ne 0 ] || fail "writer must exit non-zero when the target path is a pre-existing directory"
  assert_eq "" "$out" "no success path leaked to stdout when the target is a directory"
  assert_contains "$err" "not a regular file" "error explains the directory-at-target refusal"
  assert_dir_exists "$target"          # untouched — still the directory we created
  [ -f "$target" ] && fail "writer must not have created a regular file at the directory target"
  return 0
}

# A relative .report.output_dir must still yield an ABSOLUTE emitted path (AC #7):
# the writer resolves it against the CWD.
test_relative_output_dir_is_made_absolute() {
  local sub="rel-reports-$$" out
  # Run from inside SANDBOX so the relative dir resolves under it (and is cleaned
  # up with SANDBOX). A subshell keeps the cd local to this test.
  out="$( cd "$SANDBOX" && YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Weekly --date 2026-06-22 --output-dir "$sub" )"
  assert_eq "$SANDBOX/$sub/YNAB-Weekly-Review-2026-06-22.html" "$out" \
    "relative output dir resolved to an absolute path against the CWD"
  assert_file_exists "$out"
}

run_tests
