#!/usr/bin/env bash
#
# tests/unit/report-writer.test.sh — unit tests for bin/report-writer.sh, the
# report-assembly + output-path helper (issue #46).
#
# Follows the repo test-harness convention (issue #4, tests/lib/assert.sh): raw
# bash with `set -euo pipefail`, sources tests/lib/assert.sh, defines `test_*`
# functions, ends with `run_tests`. scripts/test.sh auto-discovers it via the
# `*.test.sh` glob — run the whole suite with `scripts/test.sh`, this file alone
# with `scripts/test.sh tests/unit/report-writer.test.sh`, or directly with
# `bash tests/unit/report-writer.test.sh`.
#
# Seams used:
#   * YNAB_CONFIG_FILE — the loader's documented test seam (a sandbox config), so
#     the .report.output_dir read is deterministic.
#   * HOME             — overridden to the sandbox so the ~-based default path and
#     ~ expansion never touch the real home directory.
#   * --template / --output-dir flags — point the writer at a tiny fixture
#     template and sandbox dirs, keeping each scenario isolated.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
source "$REPO_ROOT/tests/lib/assert.sh"

WRITER="$REPO_ROOT/bin/report-writer.sh"
REAL_TEMPLATE="$REPO_ROOT/assets/report/template.html"

SANDBOX="$(mktemp -d)"
trap 'rm -rf "$SANDBOX"' EXIT

# Sandbox HOME for the WHOLE file (not just the default-path tests): every writer
# invocation inherits it, so a resolution regression can only ever fall back to
# $SANDBOX/Documents/Claude/Reports — never the developer's real ~/Documents. The
# handful of tests that also set HOME inline (they assert on the ~-default) keep
# doing so for local clarity; this is the belt-and-braces guarantee.
export HOME="$SANDBOX"

# A tiny fixture template with three block slots + the three scalar slots, so the
# behavioural tests are not coupled to the real template's full slot list. The
# writer derives "required" from whatever the template declares.
FIXTURE_TEMPLATE="$SANDBOX/template.html"
cat > "$FIXTURE_TEMPLATE" <<'HTML'
<!DOCTYPE html><html><head>
<title>{{tier}} YNAB Review — {{report_date}}</title>
<meta name="report-output-path" content="{{output_path}}">
</head><body>
<section class="section"><!-- SLOT:kpi-dashboard --></section>
<section class="section"><!-- SLOT:section-1-classification --></section>
<footer class="print-footer">Generated by <!-- SLOT:footer-persona --></footer>
</body></html>
HTML

# The fixture template's three block slots, as `--slot name=value` argv, with
# real-ish HTML so substitution faithfulness is exercised.
fixture_slots() {
  printf '%s\0' \
    '--slot' 'kpi-dashboard=<div class="kpi-grid"><div class="kpi">Income 1,234</div></div>' \
    '--slot' 'section-1-classification=<div class="card"><h2>Classification</h2></div>' \
    '--slot' 'footer-persona=Hobbes'
}

# Run the writer with the fixture template + fixture slots, plus any extra argv.
# Reads NUL-delimited args so HTML values with spaces/'=' survive intact.
run_writer_fixture() {
  local args=()
  while IFS= read -r -d '' a; do args+=("$a"); done < <(fixture_slots)
  YNAB_CONFIG_FILE="${YNAB_CONFIG_FILE:-$SANDBOX/none.json}" \
    bash "$WRITER" --template "$FIXTURE_TEMPLATE" "$@" "${args[@]}"
}

# (a) AC: default path applied when .report.output_dir is absent from config.
#     HOME → sandbox, so the ~/Documents/Claude/Reports default lands in sandbox.
test_default_path_when_config_absent() {
  local out
  out="$(HOME="$SANDBOX" YNAB_CONFIG_FILE="$SANDBOX/missing.json" \
          run_writer_fixture --tier Weekly --date 2026-06-22)"
  assert_eq "$SANDBOX/Documents/Claude/Reports/YNAB-Weekly-Review-2026-06-22.html" "$out" \
    "default ~/Documents/Claude/Reports applied + filename built"
  assert_file_exists "$out"
}

# (b) AC: custom configured path used when .report.output_dir is present.
test_custom_path_from_config() {
  local cfg="$SANDBOX/with-dir.json" dir="$SANDBOX/configured-reports" out
  cat > "$cfg" <<JSON
{ "report": { "output_dir": "$dir" } }
JSON
  out="$(YNAB_CONFIG_FILE="$cfg" run_writer_fixture --tier Monthly --date 2026-01-31)"
  assert_eq "$dir/YNAB-Monthly-Review-2026-01-31.html" "$out" "configured output_dir used"
  assert_file_exists "$out"
}

# (c) AC: missing required slot (not marked `no findings`) → non-zero, no file.
test_missing_slot_fails_and_writes_nothing() {
  local dir="$SANDBOX/should-stay-empty" rc=0 out err
  # Only two of the fixture's three block slots supplied — footer-persona omitted.
  # stdout and stderr captured SEPARATELY so we can assert the error text AND
  # that no success path leaked to stdout.
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$dir" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-dashboard=<div>x</div>' \
            --slot 'section-1-classification=<div>y</div>' 2>"$SANDBOX/missing.err" )" || rc=$?
  err="$(cat "$SANDBOX/missing.err")"
  assert_eq "1" "$rc" "exit code is non-zero (1) on a missing required slot"
  assert_eq "" "$out" "no success path leaked to stdout on a missing slot"
  assert_contains "$err" "footer-persona" "error names the missing slot"
  # No file — and the writer must not even create the output file.
  [ -e "$dir/YNAB-Weekly-Review-2026-06-22.html" ] \
    && fail "writer wrote a file despite a missing required slot"
  return 0
}

# An empty value (without the sentinel) is treated as missing — no partial files.
test_empty_value_is_treated_as_missing() {
  local rc=0 out err
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$SANDBOX/empties" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-dashboard=<div>x</div>' \
            --slot 'section-1-classification=<div>y</div>' \
            --slot 'footer-persona=' 2>"$SANDBOX/empty.err" )" || rc=$?
  err="$(cat "$SANDBOX/empty.err")"
  assert_eq "1" "$rc" "empty slot value (no sentinel) is rejected"
  assert_eq "" "$out" "no success path leaked to stdout on an empty slot"
  assert_contains "$err" "footer-persona" "error names the empty slot"
  # "no partial files" must hold for an empty value too — assert nothing written.
  [ -e "$SANDBOX/empties/YNAB-Weekly-Review-2026-06-22.html" ] \
    && fail "writer wrote a file despite an empty (un-sentineled) slot"
  return 0
}

# A whitespace-only value ("   ") is trimmed and judged empty — the completeness
# guard must reject it (no silently-blank section), exactly like an empty value.
test_whitespace_only_slot_is_treated_as_missing() {
  local dir="$SANDBOX/whitespace" rc=0 out err
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$dir" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-dashboard=<div>x</div>' \
            --slot 'section-1-classification=<div>y</div>' \
            --slot 'footer-persona=   ' 2>"$SANDBOX/ws.err" )" || rc=$?
  err="$(cat "$SANDBOX/ws.err")"
  assert_eq "1" "$rc" "a whitespace-only slot value is rejected as missing"
  assert_eq "" "$out" "no success path leaked to stdout on a whitespace-only slot"
  assert_contains "$err" "footer-persona" "error names the blank slot"
  [ -e "$dir/YNAB-Weekly-Review-2026-06-22.html" ] \
    && fail "writer wrote a file despite a whitespace-only slot"
  return 0
}

# `no findings` is the explicit "intentionally empty" sentinel: it satisfies the
# completeness check and renders as an empty section (no literal text leaks).
test_no_findings_sentinel_allows_write() {
  local dir="$SANDBOX/sentinel" out body
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$dir" \
            --tier Annual --date 2026-12-31 \
            --slot 'kpi-dashboard=<div>k</div>' \
            --slot 'section-1-classification=no findings' \
            --slot 'footer-persona=Hobbes' )"
  assert_file_exists "$out"
  body="$(cat "$out")"
  assert_contains "$body" '<section class="section"></section>' "sentinel slot rendered empty"
  case "$body" in *"no findings"*) fail "literal 'no findings' leaked into the report" ;; esac
}

# Filename format, ~ expansion, and trailing-slash tolerance all at once.
test_tilde_and_trailing_slash() {
  local out
  # The literal ~ is the value UNDER TEST — the writer expands it, not the shell.
  # shellcheck disable=SC2088
  out="$( HOME="$SANDBOX" YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Quarterly-Tax --date 2026-04-15 \
            --output-dir '~/reports/' )"
  assert_eq "$SANDBOX/reports/YNAB-Quarterly-Tax-Review-2026-04-15.html" "$out" \
    "~ expanded, trailing slash collapsed, tier kept verbatim in filename"
  assert_file_exists "$out"
}

# Scalar slots substituted; no slot comment or mustache placeholder survives.
test_scalar_slots_substituted() {
  local out body
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Monthly --date 2026-02-28 \
            --output-dir "$SANDBOX/scalars" )"
  body="$(cat "$out")"
  assert_contains "$body" "Monthly YNAB Review — 2026-02-28" "{{tier}} + {{report_date}} substituted"
  assert_contains "$body" "content=\"$out\"" "{{output_path}} substituted with the saved path"
  case "$body" in *"<!-- SLOT:"*) fail "an unfilled SLOT comment survived" ;; esac
  case "$body" in *"{{"*) fail "an unfilled {{scalar}} placeholder survived" ;; esac
}

# Bad tier / bad date / unknown slot are usage errors (exit 2).
test_usage_errors() {
  local rc=0
  rc=0; YNAB_CONFIG_FILE="$SANDBOX/none.json" run_writer_fixture --tier Daily --date 2026-06-22 >/dev/null 2>&1 || rc=$?
  assert_eq "2" "$rc" "invalid tier → exit 2"
  rc=0; YNAB_CONFIG_FILE="$SANDBOX/none.json" run_writer_fixture --tier Weekly --date 06-22-2026 >/dev/null 2>&1 || rc=$?
  assert_eq "2" "$rc" "invalid date → exit 2"
  rc=0
  YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" --template "$FIXTURE_TEMPLATE" \
    --output-dir "$SANDBOX/u" --tier Weekly --date 2026-06-22 \
    --slot 'kpi-dashboard=a' --slot 'section-1-classification=b' \
    --slot 'footer-persona=c' --slot 'no-such-slot=x' >/dev/null 2>&1 || rc=$?
  assert_eq "2" "$rc" "unknown slot name → exit 2"
}

# Integration against the REAL frozen template: all 14 slots filled, nothing left.
test_real_template_all_slots() {
  local dir="$SANDBOX/real" out body
  assert_file_exists "$REAL_TEMPLATE"
  local args=()
  local s
  for s in kpi-dashboard \
           section-1-classification section-2-income section-3-spending \
           section-4-budget-adherence section-5-cash-flow section-6-categories \
           section-7-accounts section-8-goals section-9-net-worth \
           section-10-anomalies section-11-recommendations section-12-tax-summary \
           footer-persona; do
    args+=( --slot "$s=<!-- filled:$s -->" )
  done
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$REAL_TEMPLATE" --output-dir "$dir" \
            --tier Annual --date 2026-12-31 "${args[@]}" )"
  assert_eq "$dir/YNAB-Annual-Review-2026-12-31.html" "$out" "real-template report path"
  body="$(cat "$out")"
  case "$body" in *"<!-- SLOT:"*) fail "a real-template SLOT comment was left unfilled" ;; esac
  case "$body" in *"{{tier}}"*|*"{{report_date}}"*|*"{{output_path}}"*) fail "a real-template scalar slot survived" ;; esac
  assert_contains "$body" "Annual YNAB Review" "real-template header tier filled"
}

# A typo'd required-slot name must surface as an UNKNOWN name, not silently hide
# behind the real slot's "missing" report — else the caller never sees the typo.
test_slot_typo_surfaces_unknown_name() {
  local dir="$SANDBOX/typo" rc=0 out err
  # kpi-dashboard MISSPELLED kpi-dashboad: the real slot is now unfilled, and the
  # typo'd name is unknown to the template. (Neither name is a substring of the
  # other, so each assertion below is unambiguous.)
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$dir" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-dashboad=<div>x</div>' \
            --slot 'section-1-classification=<div>y</div>' \
            --slot 'footer-persona=Hobbes' 2>"$SANDBOX/typo.err" )" || rc=$?
  err="$(cat "$SANDBOX/typo.err")"
  assert_eq "1" "$rc" "a missing real slot still sets exit 1 even with a typo present"
  assert_eq "" "$out" "no success path leaked to stdout on a typo'd slot"
  assert_contains "$err" "kpi-dashboad" "error surfaces the unknown (typo'd) slot name"
  assert_contains "$err" "kpi-dashboard" "error still names the genuinely-missing slot"
  [ -e "$dir/YNAB-Weekly-Review-2026-06-22.html" ] \
    && fail "writer wrote a file despite a typo'd slot"
  return 0
}

# An invalid --slot name (glob metachar / uppercase) is rejected at PARSE time
# (exit 2) so it can never reach the literal substitution needle.
test_invalid_slot_name_rejected_at_parse() {
  local rc=0 err
  err="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$SANDBOX/badname" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-*=<div>x</div>' 2>&1 )" || rc=$?
  assert_eq "2" "$rc" "glob-metachar slot name → usage error (exit 2)"
  assert_contains "$err" "invalid --slot name" "error explains the bad slot name"
}

# A configured output_dir that resolves to EMPTY — a SET-but-empty $VAR — is
# refused rather than silently writing to the filesystem root. (An UNSET $VAR is
# refused earlier still, by expand_path itself — see the next test.) The var is
# exported so the writer subprocess sees it SET-but-empty; expand_path resolves
# it to "" and the writer's own empty-path guard (line ~213) rejects it.
test_empty_output_dir_is_rejected() {
  local cfg="$SANDBOX/empty-dir.json" rc=0 err
  export YNAB_SET_EMPTY_DIR=""
  cat > "$cfg" <<'JSON'
{ "report": { "output_dir": "$YNAB_SET_EMPTY_DIR" } }
JSON
  err="$( YNAB_CONFIG_FILE="$cfg" run_writer_fixture --tier Weekly --date 2026-06-22 2>&1 )" || rc=$?
  unset YNAB_SET_EMPTY_DIR
  assert_eq "2" "$rc" "output dir resolving to empty → usage error (exit 2)"
  assert_contains "$err" "output dir resolved to empty" "error explains the empty output dir"
}

# An UNSET $VAR — whether it is the whole value or only PART of a longer path — is
# REFUSED by expand_path, not silently swallowed to "". `$TYPO/reports` with TYPO
# unset must NOT collapse to `/reports` (a valid-looking absolute path the
# empty-check never fires on) and send the writer to the filesystem root; the
# resolver fails so the writer exits 2 "did not fully resolve". The single-quoted
# heredoc keeps `$YNAB_DEFINITELY_UNSET_VAR` UNEXPANDED so expand_path is exercised.
test_unset_var_embedded_in_output_dir_is_refused() {
  local cfg="$SANDBOX/unset-embedded.json" rc=0 err
  cat > "$cfg" <<'JSON'
{ "report": { "output_dir": "$YNAB_DEFINITELY_UNSET_VAR/reports" } }
JSON
  err="$( YNAB_CONFIG_FILE="$cfg" run_writer_fixture --tier Weekly --date 2026-06-22 2>&1 )" || rc=$?
  assert_eq "2" "$rc" "an unset \$VAR embedded in output_dir → usage error (exit 2)"
  assert_contains "$err" "did not fully resolve" "error explains the unresolved output dir"
}

# #28 cost invariant: .report.output_dir is config-sourced and unbounded, and
# both the trailing-slash loop and html_escape's {{output_path}} substitution
# are super-linear on match-dense input (32 KB of '&' ≈ 2 min on bash 3.2) —
# so an over-1024-byte out_dir is refused loudly BEFORE either pass can run on
# it. Watchdog-wrapped: a regression would otherwise peg the suite for minutes.
test_overlong_output_dir_is_rejected_in_bounded_time() {
  local cfg="$SANDBOX/overlong-dir.json" flood="" i=0 rc=0 pid waited=0
  while [ "$i" -lt 4096 ]; do flood+='&&&&&&&&'; i=$((i + 1)); done   # ~32 KB of '&'
  printf '{ "report": { "output_dir": "/tmp/%s" } }' "$flood" > "$cfg"
  ( YNAB_CONFIG_FILE="$cfg" run_writer_fixture --tier Weekly --date 2026-06-22 \
      >"$SANDBOX/overlong-out" 2>"$SANDBOX/overlong-err" ) &
  pid=$!
  while kill -0 "$pid" 2>/dev/null; do
    if [ "$waited" -ge 20 ]; then
      kill -9 "$pid" 2>/dev/null; wait "$pid" 2>/dev/null || true
      fail "overlong output_dir overran the 20 s watchdog (unbounded scan regressed)"
    fi
    sleep 1; waited=$((waited + 1))
  done
  wait "$pid" || rc=$?
  assert_eq "2" "$rc" "over-1024-byte output dir → usage error (exit 2)"
  assert_contains "$(cat "$SANDBOX/overlong-err")" "longer than 1024 bytes" "error names the bound"
  assert_contains "$(cat "$SANDBOX/overlong-err")" ".report.output_dir" "error names the field"
}

# #28 round-6 blocker: the 1024-"byte" gate used a bare `${#out_dir}` — a
# CHARACTER count under a UTF-8 locale — so a ~517-char / ~1.5 KB-byte multibyte
# output_dir cleared a bound documented as PATH_MAX bytes and rolled on toward
# mkdir. The ASCII fixture above never catches this (bytes == chars for ASCII);
# this one FORCES a UTF-8 locale so the char/byte divergence is live regardless
# of the harness's ambient locale (under LC_ALL=C even the buggy gate refuses it).
test_multibyte_output_dir_gate_counts_bytes_not_chars() {
  local cfg="$SANDBOX/multibyte-dir.json" loc unit path i=0 rc=0 err
  loc="$(locale -a 2>/dev/null | grep -Eim1 '^(c|en_us)\.utf-?8$' || true)"
  [ -n "$loc" ] || loc="en_US.UTF-8"
  unit="$(printf '\xe6\x97\xa5')"                              # 日 — 1 char, 3 bytes
  path="$unit"
  while [ "$i" -lt 9 ]; do path+="$path"; i=$((i + 1)); done   # 512 chars, 1536 bytes
  printf '{ "report": { "output_dir": "/tmp/%s" } }' "$path" > "$cfg"
  err="$( LC_ALL="$loc" YNAB_CONFIG_FILE="$cfg" run_writer_fixture \
            --tier Weekly --date 2026-06-22 2>&1 >/dev/null )" || rc=$?
  assert_eq "2" "$rc" "517-char / 1541-byte output dir → usage error (the gate must count bytes)"
  assert_contains "$err" "longer than 1024 bytes" "error names the byte bound"
  assert_contains "$err" ".report.output_dir" "error names the field"
}

# Regression for the write-failure gate (prior round's blocker #1): when the
# output dir cannot be created — its parent is a regular FILE, so `mkdir -p`
# fails deterministically for any user — the writer must exit non-zero, write NO
# file, and print NOTHING to stdout. Every "writes nothing" test above stops at
# the pre-write completeness check; this one exercises the write path itself.
test_write_failure_gate() {
  local blocker="$SANDBOX/not-a-dir" rc=0 out
  : > "$blocker"                       # a regular file where a directory is needed
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$blocker/sub" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-dashboard=<div>k</div>' \
            --slot 'section-1-classification=<div>s</div>' \
            --slot 'footer-persona=Hobbes' 2>/dev/null )" || rc=$?
  [ "$rc" -ne 0 ] || fail "writer must exit non-zero when the output dir can't be created"
  assert_eq "" "$out" "no success path leaked to stdout on a write failure"
  [ -e "$blocker/sub/YNAB-Weekly-Review-2026-06-22.html" ] \
    && fail "writer wrote a file despite a write failure"
  return 0
}

# Multiple trailing slashes collapse to a single separator (the pre-fix
# `${out_dir%/}` only stripped one — this guards the loop that strips them all).
test_multi_trailing_slash_collapsed() {
  local out
  out="$( HOME="$SANDBOX" YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Weekly --date 2026-06-22 \
            --output-dir "$SANDBOX/multi///" )"
  assert_eq "$SANDBOX/multi/YNAB-Weekly-Review-2026-06-22.html" "$out" \
    "multiple trailing slashes collapsed to a single path separator"
  assert_file_exists "$out"
}

# .report.template_path is resolved from config when --template is absent.
test_template_path_from_config() {
  local cfg="$SANDBOX/tmpl.json" out args=()
  cat > "$cfg" <<JSON
{ "report": { "template_path": "$FIXTURE_TEMPLATE" } }
JSON
  while IFS= read -r -d '' a; do args+=("$a"); done < <(fixture_slots)
  out="$( YNAB_CONFIG_FILE="$cfg" bash "$WRITER" \
            --output-dir "$SANDBOX/tmpl-out" \
            --tier Weekly --date 2026-06-22 "${args[@]}" )"
  assert_eq "$SANDBOX/tmpl-out/YNAB-Weekly-Review-2026-06-22.html" "$out" \
    ".report.template_path used when --template is absent"
  assert_file_exists "$out"
}

# With neither --template nor .report.template_path, the bundled asset template
# (assets/report/template.html) is the fallback — pass its full real slot set.
test_bundled_default_template_fallback() {
  local dir="$SANDBOX/bundled" out args=() s
  for s in kpi-dashboard \
           section-1-classification section-2-income section-3-spending \
           section-4-budget-adherence section-5-cash-flow section-6-categories \
           section-7-accounts section-8-goals section-9-net-worth \
           section-10-anomalies section-11-recommendations section-12-tax-summary \
           footer-persona; do
    args+=( --slot "$s=<!-- filled:$s -->" )
  done
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --output-dir "$dir" --tier Weekly --date 2026-06-22 "${args[@]}" )"
  assert_eq "$dir/YNAB-Weekly-Review-2026-06-22.html" "$out" \
    "bundled default template used when neither flag nor config sets one"
  assert_file_exists "$out"
}

# A configured/flag template that does not exist is a usage error (exit 2).
test_template_not_found_is_usage_error() {
  local rc=0 err
  # The trailing --template overrides run_writer_fixture's fixture path.
  err="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --template "$SANDBOX/does-not-exist.html" \
            --tier Weekly --date 2026-06-22 2>&1 )" || rc=$?
  assert_eq "2" "$rc" "a nonexistent template → usage error (exit 2)"
  assert_contains "$err" "template not found" "error explains the missing template"
}

# {{tier}} renders the friendly display name (Quarterly-Tax → "Quarterly Tax"),
# while the filename keeps the hyphenated enum.
test_quarterly_tax_display_name() {
  local dir="$SANDBOX/qt" out body
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Quarterly-Tax --date 2026-04-15 \
            --output-dir "$dir" )"
  assert_eq "$dir/YNAB-Quarterly-Tax-Review-2026-04-15.html" "$out" \
    "filename keeps the hyphenated Quarterly-Tax enum"
  body="$(cat "$out")"
  assert_contains "$body" "Quarterly Tax YNAB Review" "{{tier}} renders the friendly 'Quarterly Tax'"
  case "$body" in *"Quarterly-Tax YNAB Review"*) fail "hyphenated enum leaked into the {{tier}} display" ;; esac
}

# The writer HTML-escapes {{output_path}} — a configured path with HTML
# metacharacters must never break out of the meta attribute / inject an element.
test_output_path_is_html_escaped() {
  # The leading '&' also guards bash 5.2's patsub_replacement: a literal '&' in a
  # ${var//pat/repl} replacement must NOT expand to the matched text (which would
  # yield `<lt;` instead of `&lt;` and defeat the escaping).
  local danger='inj&"><script>x' dir out body
  dir="$SANDBOX/$danger"               # a single dir component (no '/'), dangerous chars
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Weekly --date 2026-06-22 --output-dir "$dir" )"
  assert_file_exists "$out"
  body="$(cat "$out")"
  assert_contains "$body" 'inj&amp;&quot;&gt;&lt;script&gt;x' "output path is HTML-escaped in the report"
  case "$body" in
    *'"><script>x'*) fail "unescaped output path broke out of the attribute (element injection)" ;;
    *'<lt;'*|*'>gt;'*) fail "patsub_replacement corrupted the HTML entities (& → matched text)" ;;
  esac
}

# An output dir resolving to the bare filesystem root is refused (exit 2), never
# written to as "/YNAB-…html".
test_root_output_dir_is_rejected() {
  local rc=0 err
  err="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Weekly --date 2026-06-22 --output-dir '/' 2>&1 )" || rc=$?
  assert_eq "2" "$rc" "output dir resolving to '/' → usage error (exit 2)"
  assert_contains "$err" "filesystem root" "error explains the root refusal"
}

# Out-of-range dates (month 13, day 39) are rejected, not just malformed shapes.
test_out_of_range_date_is_rejected() {
  local rc
  rc=0; YNAB_CONFIG_FILE="$SANDBOX/none.json" run_writer_fixture --tier Weekly --date 2026-13-01 >/dev/null 2>&1 || rc=$?
  assert_eq "2" "$rc" "month 13 → exit 2"
  rc=0; YNAB_CONFIG_FILE="$SANDBOX/none.json" run_writer_fixture --tier Weekly --date 2026-06-39 >/dev/null 2>&1 || rc=$?
  assert_eq "2" "$rc" "day 39 → exit 2"
}

# Regression: when the target path already exists as a DIRECTORY, `mv file dir`
# on BSD/macOS moves the temp file *into* it and exits 0 — a false success. The
# writer must refuse (non-zero), print no path, and leave no report file at the
# target. Gating test for the pre-`mv` "not a regular file" guard.
test_pre_existing_dir_at_target_is_refused() {
  local dir="$SANDBOX/dir-target" rc=0 out err target
  target="$dir/YNAB-Weekly-Review-2026-06-22.html"
  mkdir -p "$target"                   # the exact deterministic filename, as a directory
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$dir" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-dashboard=<div>k</div>' \
            --slot 'section-1-classification=<div>s</div>' \
            --slot 'footer-persona=Hobbes' 2>"$SANDBOX/dir-target.err" )" || rc=$?
  err="$(cat "$SANDBOX/dir-target.err")"
  [ "$rc" -ne 0 ] || fail "writer must exit non-zero when the target path is a pre-existing directory"
  assert_eq "" "$out" "no success path leaked to stdout when the target is a directory"
  assert_contains "$err" "not a regular file" "error explains the directory-at-target refusal"
  assert_dir_exists "$target"          # untouched — still the directory we created
  [ -f "$target" ] && fail "writer must not have created a regular file at the directory target"
  return 0
}

# A relative .report.output_dir must still yield an ABSOLUTE emitted path (AC #7):
# the writer resolves it against the CWD.
test_relative_output_dir_is_made_absolute() {
  local sub="rel-reports-$$" out
  # Run from inside SANDBOX so the relative dir resolves under it (and is cleaned
  # up with SANDBOX). A subshell keeps the cd local to this test.
  out="$( cd "$SANDBOX" && YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Weekly --date 2026-06-22 --output-dir "$sub" )"
  assert_eq "$SANDBOX/$sub/YNAB-Weekly-Review-2026-06-22.html" "$out" \
    "relative output dir resolved to an absolute path against the CWD"
  assert_file_exists "$out"
}

# Regression (round-4 blocker 1): a block fragment whose value literally contains
# ANOTHER slot's marker must NOT have that marker rewritten when the later slot is
# filled. The single-pass fill appends each resolved fragment to an accumulator
# that is never re-scanned, so an embedded `<!-- SLOT:name -->` survives verbatim
# instead of one section's content being spliced into another. A per-slot global
# `${html//needle/value}` would corrupt it — this test fails against that approach.
test_fragment_containing_another_slot_marker_is_not_corrupted() {
  local dir="$SANDBOX/cross-slot" out body
  # kpi-dashboard's value embeds footer-persona's marker; footer-persona is
  # supplied and filled AFTER it in the template. A re-scanning fill would splice
  # "Hobbes" into the kpi fragment's embedded marker.
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$dir" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-dashboard=<div>see <!-- SLOT:footer-persona --> below</div>' \
            --slot 'section-1-classification=<div>y</div>' \
            --slot 'footer-persona=Hobbes' )"
  assert_file_exists "$out"
  body="$(cat "$out")"
  # The embedded marker inside the kpi fragment is left verbatim (not replaced)…
  assert_contains "$body" '<div>see <!-- SLOT:footer-persona --> below</div>' \
    "an embedded slot marker inside a fragment value is left verbatim"
  # …while the GENUINE footer-persona slot in the template chrome is still filled.
  assert_contains "$body" 'Generated by Hobbes' "the real footer-persona slot is filled"
}

# AC #4 positive path: an environment variable referenced in .report.output_dir is
# resolved to its VALUE (the `~` branch is covered elsewhere; this exercises the
# `$VAR` loop). The heredoc is SINGLE-quoted so `$YNAB_REPORTS_*` reach the writer
# UNEXPANDED — the parent shell must not pre-expand them, or expand_path is never
# tested. The TRANSITIVE case is covered too: the referenced variable's own value
# contains a second `$VAR` that must also resolve.
test_env_var_in_output_dir_is_resolved() {
  local cfg="$SANDBOX/env-dir.json" out
  cat > "$cfg" <<'JSON'
{ "report": { "output_dir": "$YNAB_REPORTS_BASE/nested" } }
JSON
  # Exported so the writer subprocess inherits them. YNAB_REPORTS_BASE's value
  # itself contains $YNAB_REPORTS_ROOT → expand_path must re-scan and resolve it.
  export YNAB_REPORTS_ROOT="$SANDBOX/env-root"
  # The single quotes are the point: $YNAB_REPORTS_ROOT must survive UNEXPANDED
  # into YNAB_REPORTS_BASE's value so expand_path resolves it transitively.
  # shellcheck disable=SC2016
  export YNAB_REPORTS_BASE='$YNAB_REPORTS_ROOT/base'
  out="$( YNAB_CONFIG_FILE="$cfg" run_writer_fixture --tier Weekly --date 2026-06-22 )"
  unset YNAB_REPORTS_ROOT YNAB_REPORTS_BASE
  assert_eq "$SANDBOX/env-root/base/nested/YNAB-Weekly-Review-2026-06-22.html" "$out" \
    "\$VAR (and its own nested \$VAR) in output_dir resolved to the variable's value"
  assert_file_exists "$out"
}

# Non-blocking follow-up (round 4): a SECOND report written into a directory the
# writer already created must succeed (`mkdir -p` is idempotent) and must leave a
# prior good report at a different filename in that directory untouched.
test_rerun_into_existing_dir_preserves_prior_report() {
  local dir="$SANDBOX/rerun" first second
  first="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" \
            run_writer_fixture --tier Weekly --date 2026-06-22 --output-dir "$dir" )"
  assert_file_exists "$first"
  # Second run into the now-existing dir; different tier/date → different filename.
  second="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" \
             run_writer_fixture --tier Monthly --date 2026-07-31 --output-dir "$dir" )"
  assert_file_exists "$second"
  assert_file_exists "$first"          # the first report survives the second run
}

# Regression (round-2-since-reset blocker): a MALFORMED template marker must fail
# LOUDLY (exit 2, no file), never be swallowed into a silently-corrupt exit-0
# report. Shape 1 — an UNCLOSED opener before a real, supplied marker: the old
# `%%` name-grab consumed the tail as a composite name, the real slot was never
# filled, and the writer wrote a byte-identical-to-template report at exit 0.
test_unclosed_template_marker_is_refused() {
  local tmpl="$SANDBOX/unclosed.html" dir="$SANDBOX/unclosed-out" rc=0 out err
  # `<!-- SLOT:foo` is never closed; `<!-- SLOT:bar -->` is a genuine slot. Without
  # the guard the fill loop drops `bar` and exits 0 (Holmes's exact repro).
  printf '<!-- SLOT:foo\n<!-- SLOT:bar -->\n' > "$tmpl"
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$tmpl" --output-dir "$dir" \
            --tier Weekly --date 2026-06-22 \
            --slot 'bar=<p>REAL</p>' 2>"$SANDBOX/unclosed.err" )" || rc=$?
  err="$(cat "$SANDBOX/unclosed.err")"
  assert_eq "2" "$rc" "an unclosed SLOT marker → usage error (exit 2)"
  assert_eq "" "$out" "no success path leaked to stdout for a malformed template"
  assert_contains "$err" "malformed" "error explains the malformed template"
  [ -e "$dir/YNAB-Weekly-Review-2026-06-22.html" ] \
    && fail "writer wrote a file despite a malformed template"
  return 0
}

# Shape 2 — a malformed opener BEFORE a real marker on ONE line: the old `%%`
# match extended the name through the genuine marker's ` -->`, so the real slot
# was silently never filled (exit 0). The guard rejects it before any write.
test_malformed_opener_before_real_marker_is_refused() {
  local tmpl="$SANDBOX/malopener.html" dir="$SANDBOX/malopener-out" rc=0 out err
  printf '<body>Head <!-- SLOT:oops something <!-- SLOT:real --> Tail</body>\n' > "$tmpl"
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$tmpl" --output-dir "$dir" \
            --tier Weekly --date 2026-06-22 \
            --slot 'real=REALVALUE' 2>"$SANDBOX/malopener.err" )" || rc=$?
  err="$(cat "$SANDBOX/malopener.err")"
  assert_eq "2" "$rc" "a malformed opener before a real marker → usage error (exit 2)"
  assert_eq "" "$out" "no success path leaked to stdout for a malformed template"
  assert_contains "$err" "malformed" "error explains the malformed template"
  [ -e "$dir/YNAB-Weekly-Review-2026-06-22.html" ] \
    && fail "writer wrote a file despite a malformed template"
  return 0
}

# AC #4 (braced form): the BRACED `${VAR}` env-var syntax — not just bare `$VAR` —
# in .report.output_dir is resolved to the variable's value. Mutation-confirmed
# gap last round: deleting the `${…}` alternative from expand_path's regex left
# the bare-$VAR test green. Single-quoted heredoc so `${VAR}` reaches the writer
# UNEXPANDED (the parent shell must not pre-expand it).
test_braced_env_var_in_output_dir_is_resolved() {
  local cfg="$SANDBOX/braced-env-dir.json" out
  cat > "$cfg" <<'JSON'
{ "report": { "output_dir": "${YNAB_REPORTS_BRACED}/nested" } }
JSON
  export YNAB_REPORTS_BRACED="$SANDBOX/braced-root"
  out="$( YNAB_CONFIG_FILE="$cfg" run_writer_fixture --tier Weekly --date 2026-06-22 )"
  unset YNAB_REPORTS_BRACED
  assert_eq "$SANDBOX/braced-root/nested/YNAB-Weekly-Review-2026-06-22.html" "$out" \
    "braced \${VAR} in output_dir resolved to the variable's value"
  assert_file_exists "$out"
}

# Non-blocking follow-up (round 2 since reset): a DUPLICATE --slot name is
# rejected at PARSE time (exit 2) rather than silently keeping the first value —
# the opposite of the conventional last-wins idiom, and a near-certain caller bug
# for a strict one-`--slot`-per-block-slot contract.
test_duplicate_slot_name_is_rejected() {
  local rc=0 err
  err="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" bash "$WRITER" \
            --template "$FIXTURE_TEMPLATE" --output-dir "$SANDBOX/dup" \
            --tier Weekly --date 2026-06-22 \
            --slot 'kpi-dashboard=<div>first</div>' \
            --slot 'kpi-dashboard=<div>second</div>' \
            --slot 'section-1-classification=<div>y</div>' \
            --slot 'footer-persona=Hobbes' 2>&1 )" || rc=$?
  assert_eq "2" "$rc" "a duplicate --slot name → usage error (exit 2)"
  assert_contains "$err" "duplicate --slot name" "error explains the duplicate slot"
  [ -e "$SANDBOX/dup/YNAB-Weekly-Review-2026-06-22.html" ] \
    && fail "writer wrote a file despite a duplicate --slot name"
  return 0
}

# Non-blocking follow-up (defense-in-depth): html_escape also escapes the
# apostrophe (`&#39;`), so an output path containing a single quote is inert even
# if a future template ever placed {{output_path}} inside a single-quoted attr.
test_output_path_single_quote_is_escaped() {
  local dir="$SANDBOX/quote'd-reports" out body
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Weekly --date 2026-06-22 --output-dir "$dir" )"
  assert_file_exists "$out"
  body="$(cat "$out")"
  assert_contains "$body" "&#39;" "a single quote in the output path is escaped to &#39;"
  case "$body" in *"quote'd-reports"*) fail "a raw single quote leaked into the report body" ;; esac
}

# Security regression (round-1 follow-up): command / arithmetic substitution in
# .report.output_dir is NEVER executed. expand_path resolves only $VAR / ${VAR},
# so `$(…)`, backticks, and `$((…))` land as INERT LITERAL directory-name text —
# an eval would run the payload. Pins the no-eval property (mutation: swapping
# expand_path for an eval creates $marker → this test goes red).
test_command_substitution_in_output_dir_is_inert() {
  local marker="$SANDBOX/PWNED" cfg="$SANDBOX/inert.json" dir out
  rm -f "$marker"
  # A dir name embedding $(…), `…`, and $((…)). Backslash-escaped so the PARENT
  # shell never evaluates them either — only the writer's expand_path sees them.
  # $marker interpolates to an absolute path (no literal $ left for the writer).
  dir="$SANDBOX/inert-\$(touch $marker)-\`touch $marker\`-\$((99))"
  # printf writes the payload LITERALLY into the config (%s), so nothing runs at
  # config-write time — the writer is the only thing that ever reads it.
  printf '{ "report": { "output_dir": "%s" } }\n' "$dir" > "$cfg"
  out="$( YNAB_CONFIG_FILE="$cfg" run_writer_fixture --tier Weekly --date 2026-06-22 )"
  [ -e "$marker" ] && fail "a substitution in output_dir was executed — the no-eval property is broken"
  assert_file_exists "$out"
}

# Regression (blocker, shape 1): a $VAR in .report.output_dir whose VALUE begins
# with `~`. The tilde is introduced only AFTER $VAR expansion, so the old one-time
# pre-loop tilde check never saw it — expand_path returned `~/…` and the report was
# silently written to `$PWD/~/…` (exit 0). The fix resolves a leading `~` inside the
# expansion loop, so it must land under $HOME (the sandbox here). Single-quoted so
# both $VAR and the ~ in its value reach the writer UNEXPANDED (the parent shell
# must not pre-expand them). AC #4 composition — "~ AND environment variables".
test_var_value_starting_with_tilde_in_output_dir_is_resolved() {
  local cfg="$SANDBOX/tilde-alias.json" out
  cat > "$cfg" <<'JSON'
{ "report": { "output_dir": "$YNAB_DIR_ALIAS" } }
JSON
  # shellcheck disable=SC2016,SC2088
  export YNAB_DIR_ALIAS='~/tilde-reports'
  out="$( YNAB_CONFIG_FILE="$cfg" run_writer_fixture --tier Weekly --date 2026-06-22 )"
  unset YNAB_DIR_ALIAS
  assert_eq "$SANDBOX/tilde-reports/YNAB-Weekly-Review-2026-06-22.html" "$out" \
    "a \$VAR output dir whose value begins with ~ resolves under \$HOME, not \$PWD/~/…"
  assert_file_exists "$out"
}

# Regression (blocker, shape 2): a SELF-REFERENTIAL variable (FOO='$FOO/x') can
# never settle — expand_path grows it until the guard is exhausted, leaving a
# literal `$YNAB_SELFREF` in the string. The writer must REFUSE loudly (exit 2, no
# file, empty stdout) rather than write to that garbled path with exit 0.
test_self_referential_var_in_output_dir_is_refused() {
  local cfg="$SANDBOX/selfref.json" cwd="$SANDBOX/selfref-cwd" rc=0 out err
  mkdir -p "$cwd"
  cat > "$cfg" <<'JSON'
{ "report": { "output_dir": "$YNAB_SELFREF/reports" } }
JSON
  # shellcheck disable=SC2016
  export YNAB_SELFREF='$YNAB_SELFREF/x'
  out="$( cd "$cwd" && YNAB_CONFIG_FILE="$cfg" run_writer_fixture --tier Weekly --date 2026-06-22 \
            2>"$SANDBOX/selfref.err" )" || rc=$?
  unset YNAB_SELFREF
  err="$(cat "$SANDBOX/selfref.err")"
  assert_eq "2" "$rc" "a self-referential \$VAR output dir → usage error (exit 2)"
  assert_eq "" "$out" "no success path leaked to stdout for an unresolvable output dir"
  assert_contains "$err" "did not fully resolve" "the error explains the unresolved output dir"
  # No file written — the refusal fires before any mkdir/write; a broken guard's
  # relative write would land under this fresh CWD, which must stay empty.
  [ -z "$(find "$cwd" -name '*.html')" ] \
    || fail "writer wrote a report despite an unresolvable output dir"
}

# Regression (blocker, ratified option-3 completeness bar — the $VAR half): a
# self-referential value that names itself TWICE (FOO='$FOO$FOO' — a copy-paste
# doubling, e.g. OUTPUT_DIR='$OUTPUT_DIR/$OUTPUT_DIR-old') USED to defeat the
# guard: with a GLOBAL replace every pass DOUBLED the occurrence count, growing
# the string exponentially until it pegged CPU/memory and HUNG — never reaching
# the post-loop "refuse loudly" check. In automation/cron a hang is strictly
# worse than the bad-write the guard exists to prevent. Resolving only the FIRST
# reference per pass makes this grow LINEARLY (like the single-occurrence shape
# above), so it hits the cap and is refused loudly: exit 2, empty stdout, no file.
#
# This test pins BOTH properties at once. A `perl alarm` watchdog (GNU `timeout`
# is absent on macOS runners) bounds the run: if expand_path hangs (the pre-fix
# global replace), SIGALRM kills bash with a non-2 exit and the exit-2 assertion
# goes red — so the test is mutation-gated on BOUNDED COMPLETION, not merely on
# the refusal. Under the fix the writer refuses in well under the alarm window,
# so the watchdog never fires. A fresh CWD proves a broken guard's relative write
# lands nowhere. Single-quoted config + heredoc so $VAR reaches the writer UNEXPANDED.
test_double_self_referential_var_in_output_dir_is_refused_in_bounded_time() {
  local cfg="$SANDBOX/double-selfref.json" cwd="$SANDBOX/double-selfref-cwd" rc=0 out err args=()
  mkdir -p "$cwd"
  cat > "$cfg" <<'JSON'
{ "report": { "output_dir": "$YNAB_DBL_SELFREF/reports" } }
JSON
  # The value references its OWN name TWICE — the exponential-growth shape.
  # shellcheck disable=SC2016
  export YNAB_DBL_SELFREF='$YNAB_DBL_SELFREF$YNAB_DBL_SELFREF'
  while IFS= read -r -d '' a; do args+=("$a"); done < <(fixture_slots)
  # perl alarm watchdog (portable; macOS runners have no GNU `timeout`). `exec`
  # keeps the alarm timer, and bash has no SIGALRM trap so its default action
  # terminates the process → a hang exits ~142 (128+SIGALRM), never 2.
  out="$( cd "$cwd" && YNAB_CONFIG_FILE="$cfg" \
            perl -e 'alarm 5; exec @ARGV' bash "$WRITER" \
              --template "$FIXTURE_TEMPLATE" --tier Weekly --date 2026-06-22 "${args[@]}" \
            2>"$SANDBOX/double-selfref.err" )" || rc=$?
  unset YNAB_DBL_SELFREF
  err="$(cat "$SANDBOX/double-selfref.err")"
  # rc==2 pins BOTH bounded completion (a hang → watchdog SIGALRM → rc≠2 → red)
  # AND the loud refusal (a silent bad-write would be exit 0).
  assert_eq "2" "$rc" "a doubly-self-referential \$VAR output dir refuses in bounded time (exit 2, not a hang)"
  assert_eq "" "$out" "no success path leaked to stdout for an exponential self-referential output dir"
  assert_contains "$err" "did not fully resolve" "the error explains the unresolved output dir"
  [ -z "$(find "$cwd" -name '*.html')" ] \
    || fail "writer wrote a report despite an unresolvable (self-referential) output dir"
}

# Follow-up: the TEMPLATE path is resolved through the SAME expand_path, so the
# `~`-after-expansion fix must hold there too. A $VAR template_path whose value
# begins with `~` must resolve to $HOME/… (the sandbox, where the fixture lives) —
# not be left as `~/…` and reported "template not found". Single-quoted so $VAR and
# ~ both reach the writer unexpanded. (Also pins that the template caller calls
# expand_path at all: deleting that call leaves this red.)
test_template_path_var_introducing_tilde_is_resolved() {
  local cfg="$SANDBOX/tmpl-var.json" out args=()
  cat > "$cfg" <<'JSON'
{ "report": { "template_path": "$YNAB_TMPL_ALIAS" } }
JSON
  # HOME=$SANDBOX and FIXTURE_TEMPLATE=$SANDBOX/template.html, so ~/template.html
  # resolves to the fixture.
  # shellcheck disable=SC2016,SC2088
  export YNAB_TMPL_ALIAS='~/template.html'
  while IFS= read -r -d '' a; do args+=("$a"); done < <(fixture_slots)
  out="$( YNAB_CONFIG_FILE="$cfg" bash "$WRITER" \
            --output-dir "$SANDBOX/tmpl-var-out" \
            --tier Weekly --date 2026-06-22 "${args[@]}" )"
  unset YNAB_TMPL_ALIAS
  assert_eq "$SANDBOX/tmpl-var-out/YNAB-Weekly-Review-2026-06-22.html" "$out" \
    "a \$VAR template path whose value begins with ~ is fully resolved (fix holds on the template path)"
  assert_file_exists "$out"
}

# Follow-up: the template caller must also FAIL LOUDLY on an unresolvable path.
# Pins the template caller's `|| usage_err` (a self-referential template_path →
# exit 2, no file, empty stdout) — the symmetric guard to the output-dir refusal.
test_self_referential_var_in_template_path_is_refused() {
  local cfg="$SANDBOX/selfref-tmpl.json" rc=0 out err args=()
  cat > "$cfg" <<'JSON'
{ "report": { "template_path": "$YNAB_TMPL_SELFREF/t.html" } }
JSON
  # shellcheck disable=SC2016
  export YNAB_TMPL_SELFREF='$YNAB_TMPL_SELFREF/x'
  while IFS= read -r -d '' a; do args+=("$a"); done < <(fixture_slots)
  out="$( YNAB_CONFIG_FILE="$cfg" bash "$WRITER" \
            --output-dir "$SANDBOX/selfref-tmpl-out" \
            --tier Weekly --date 2026-06-22 "${args[@]}" \
            2>"$SANDBOX/selfref-tmpl.err" )" || rc=$?
  unset YNAB_TMPL_SELFREF
  err="$(cat "$SANDBOX/selfref-tmpl.err")"
  assert_eq "2" "$rc" "a self-referential \$VAR template path → usage error (exit 2)"
  assert_eq "" "$out" "no success path leaked to stdout for an unresolvable template path"
  assert_contains "$err" "template path did not fully resolve" "the error explains the unresolved template path"
  # No file written to the (valid) output dir — the template refusal fires first.
  [ -e "$SANDBOX/selfref-tmpl-out/YNAB-Weekly-Review-2026-06-22.html" ] \
    && fail "writer wrote a report despite an unresolvable template path"
  return 0
}

# Regression (blocker, ratified option-3 completeness bar): a ~USER form
# (`~mike/…`) is a tilde this helper deliberately does NOT expand — resolving
# another user's home would need eval or passwd parsing, both barred by the
# no-eval design. Before the symmetric guard it was neither resolved nor refused,
# falling through to a LITERAL `~mike` directory created under the CWD at exit 0.
# The residual-tilde guard now refuses ANY `~` beginning a path component, so a
# ~user output dir → usage error (exit 2), empty stdout, no file. A fresh CWD is
# used so a broken guard's relative write lands somewhere this test proves empty.
test_user_tilde_in_output_dir_is_refused() {
  local cwd="$SANDBOX/tilde-user-cwd" rc=0 out err
  mkdir -p "$cwd"
  # shellcheck disable=SC2088
  out="$( cd "$cwd" && run_writer_fixture --output-dir '~mike/reportsdir' \
            --tier Weekly --date 2026-06-22 2>"$SANDBOX/tilde-user.err" )" || rc=$?
  err="$(cat "$SANDBOX/tilde-user.err")"
  assert_eq "2" "$rc" "a ~user output dir → usage error (exit 2), not a literal ~mike write"
  assert_eq "" "$out" "no success path leaked to stdout for a ~user output dir"
  assert_contains "$err" "did not fully resolve" "the error explains the unresolved ~user output dir"
  [ -z "$(find "$cwd" -name '*.html')" ] \
    || fail "writer wrote a report to a literal ~user directory"
}

# Regression (blocker, same class): a `~` a variable's VALUE shoves into the
# MIDDLE of the path (`prefix/$VAR` with VAR='~/x' → `prefix/~/x`) is not a
# leading current-user tilde, so the loop never resolves it; before the symmetric
# guard it wrote to a LITERAL mid-string `~` directory at exit 0. The guard now
# refuses a `~` right after a `/` too. Single-quoted config + heredoc so $VAR and
# the ~ in its value reach the writer UNEXPANDED.
test_var_introducing_mid_string_tilde_in_output_dir_is_refused() {
  local cfg="$SANDBOX/mid-tilde.json" cwd="$SANDBOX/tilde-mid-cwd" rc=0 out err
  mkdir -p "$cwd"
  cat > "$cfg" <<'JSON'
{ "report": { "output_dir": "prefix-dir/$YNAB_MID_TILDE" } }
JSON
  # shellcheck disable=SC2016,SC2088
  export YNAB_MID_TILDE='~/embedded-reports'
  out="$( cd "$cwd" && YNAB_CONFIG_FILE="$cfg" run_writer_fixture \
            --tier Weekly --date 2026-06-22 2>"$SANDBOX/mid-tilde.err" )" || rc=$?
  unset YNAB_MID_TILDE
  err="$(cat "$SANDBOX/mid-tilde.err")"
  assert_eq "2" "$rc" "a var-introduced mid-string ~ output dir → usage error (exit 2)"
  assert_eq "" "$out" "no success path leaked to stdout for a mid-string ~ output dir"
  assert_contains "$err" "did not fully resolve" "the error explains the unresolved mid-string ~ output dir"
  [ -z "$(find "$cwd" -name '*.html')" ] \
    || fail "writer wrote a report to a literal mid-string ~ directory"
}

# Privacy hardening (issue #65, GAP-21): a report is an UNENCRYPTED financial
# record, so the WRITTEN file must be owner-only (0600) and a directory the writer
# CREATES must be owner-only (0700) — with no world-readable window at creation.
# Portable octal-perms read, GNU-first (see the note in tests/unit/audit-log.test.sh).
mode_of() { stat -c '%a' "$1" 2>/dev/null || stat -f '%Lp' "$1"; }

# A report written into a freshly-created (nested) output dir: file 0600, and
# every directory component the writer created is 0700.
test_written_report_and_created_dir_are_owner_only() {
  local dir="$SANDBOX/perms/nested" out
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Weekly --date 2026-06-22 --output-dir "$dir" )"
  assert_file_exists "$out"
  assert_eq "600" "$(mode_of "$out")"      "written report file is mode 0600"
  assert_eq "700" "$(mode_of "$dir")"      "created leaf output dir is mode 0700"
  assert_eq "700" "$(mode_of "$SANDBOX/perms")" "created parent dir is mode 0700 (umask 077, no world-readable window)"
}

# An ALREADY-EXISTING output dir is deliberately NOT force-chmod'd (the user may
# share it on purpose), but the FILE is hardened to 0600 unconditionally — its
# content is what's sensitive. Seed a loose 0755 dir + drop a report into it.
test_file_is_hardened_even_in_a_preexisting_loose_dir() {
  local dir="$SANDBOX/preexisting-loose" out
  mkdir -p "$dir"; chmod 755 "$dir"
  assert_eq "755" "$(mode_of "$dir")" "pre-existing dir starts at 0755"
  out="$( YNAB_CONFIG_FILE="$SANDBOX/none.json" \
          run_writer_fixture --tier Monthly --date 2026-02-28 --output-dir "$dir" )"
  assert_file_exists "$out"
  assert_eq "600" "$(mode_of "$out")" "report file is 0600 even inside a pre-existing loose dir"
  assert_eq "755" "$(mode_of "$dir")" "a pre-existing dir the writer did not create is left untouched"
}

run_tests
